session: ${name}
root: ${root}

windows:
  - name: " "
    commands:
      - nvim "+TelescopeFindFiles"
  - name: " "
    commands:
      - clear
  - name: "🤖 "
    layout: main-vertical
    panes:
      - commands:
          - opencode
      - type: vertical
        commands:
          - claude
